### ISSUE TITLE
The mod doesn't work with the current version of tailscale

### ISSUE THREAD

**Issue by si14** [tailscale-dev/docker-mod#9]
Tailscale 1.52.0 changed the `tailscale serve` CLI, which means this docker mode doesn't work anymore.

Current `main` call: 

```
tailscale serve "${TAILSCALE_SERVE_MODE}":443 / http://localhost:"${TAILSCALE_SERVE_PORT}"
```

I believe this should be

```
tailscale serve --bg --https=443 http://localhost:"${TAILSCALE_SERVE_PORT}"
```

instead (but I'm not fully sure if this is a full equivalent).

**Comment by rodhfr** [comment]
happend with me also

**Comment by si14** [comment]
Thanks a ton @timtailscale !
